### ISSUE TITLE
DecimalCount()

### ISSUE THREAD

**Issue by jesc7** [LindsayBradford/go-dbf#17]
// FieldType returns the count of decimal places for the field
func (fd *FieldDescriptor) DecimalCount() byte {
	return fd.length
}

May be "return fd.decimalPlaces" ?

**Comment by LindsayBradford** [comment]
Bug confirmed, and fixed with commit [ec4c15](https://github.com/LindsayBradford/go-dbf/commit/ec4c15281435b0741c120aaa2e208e7df94ec082). I renamed the method to DecimalPlaces() to make it consistent with the other methods around that field.
