### ISSUE TITLE
Consider tagging module "godbf"?

### ISSUE THREAD

**Issue by Rick-xuy** [LindsayBradford/go-dbf#27]
I found that package `github.com/LindsayBradford/go-dbf/godbf` is placed in submodule `github.com/LindsayBradford/go-dbf/godbf` instead of root module. <br>
However, it seems that submodule `github.com/LindsayBradford/go-dbf/godbf` is not tagged. According to [Go Modules wiki](https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository), submodule should be tagged like `relative-path-to-root/vX.X.X`.
At now, when trying to import package `github.com/LindsayBradford/go-dbf/godbf`, downstream would depends on **pseudo-version** of module `github.com/LindsayBradford/go-dbf/godbf`.
```
github.com/LindsayBradford/go-dbf/godbf v0.0.0-20220427112540-117aaf115530
```
I think it is not very readable and difficult to upgrade. This is not conductive to version control either.
So, I propose whether it is possible to tag submodule properly. For example, `godbf/v0.0.1`, `godbf/v1.0.0`etc, so that other project can use tag to import this module in go.mod.

**Comment by LindsayBradford** [comment]
Starting with release candidate [1.0.0-Alpha-5](https://github.com/LindsayBradford/go-dbf/releases/tag/v1.0.0-alpha-5), this should now be the case.
