### ISSUE TITLE
end-of-field marker missing from field bytes, offset [24640,24651]

### ISSUE THREAD

**Issue by minhyannv** [LindsayBradford/go-dbf#31]
The file "system.dbf" dbf come from oracle 11G by using sql "SELECT tablespace_name, file_name FROM dba_data_files WHERE tablespace_name = 'SYSTEM';"
The godbf tool get error "end-of-field marker missing from field bytes, offset [24640,24651]" while parsing the file "system.dbf"
Go code is as follows:
`package main

import (
	"fmt"
	"github.com/LindsayBradford/go-dbf/godbf"
)

func main() {
	dbfTable, err := godbf.NewFromFile("/root/system.dbf", "UTF8")

	if err != nil {
		fmt.Println(err)
		return
	}
	FieldsName := dbfTable.FieldNames()
	fmt.Println(FieldsName)

	for i := 0; i < dbfTable.NumberOfRecords(); i++ {
		rowAsSlice := dbfTable.GetRowAsSlice(i)
		fmt.Println(rowAsSlice)
	}
}
`
Can you tell me the reason？ thank you！

**Comment by razvanphp** [comment]
I get the same error with a VisualFox Pro dbf file.

**Comment by LindsayBradford** [comment]
I'm just guessing without actually having access to the file itself.

Still... the [file standard](https://en.wikipedia.org/wiki/.dbf#File_format_of_Level_5_DOS_dBASE) allocates 11 bytes to the field name, with a byte of value 0 indicating the end of the field name... A common interpretation is that the the field length is a maximum of 10, with the 11th guaranteed to be 0, though it may occur earlier.

It's possible that there is a field (or fields) allowed to be 11 bytes long, so no 0 terminator byte, triggering the error.   

It's also possible you're trying to use the library against a different (unsupportd) dBase variant. If that's the case, there's not a lot I can do to help you there.

You could try another 3rd-party tool like [DBF Viewer](https://www.dbf2002.com/order.html).  It might shed some light on field lengths and/or file standard your DBF file says its compatible with.
