### ISSUE TITLE
how save to file

### ISSUE THREAD

**Issue by lppgo** [LindsayBradford/go-dbf#33]
dbfFile.SaveToFile undefined (type *godbf.DbfTable has no field or method SaveToFile)

**Comment by LindsayBradford** [comment]
Oops. I've broken something. Stay tuned.

**Comment by zxbfeng** [comment]
Hi, This dbf library is not  high efficiency。For example, to read records about the new added records, we have not interface to set the offset bytes, so  we should read from the start of the file and read each row.  and we want to write a new record to the end we should write the old records every time

**Comment by LindsayBradford** [comment]
It works on a model of pulling everything into memory, and saving the entire updated byte-array back to disk when done.  Efficient is debatable.. this model works well for multiple changes for smaller file sizes that can be easily held in memory, minimising the slower disk access operations that would result with your suggestion.  

As we're targetting ESRI Shapefille support, [DBF files are limited to 2Gb](https://en.wikipedia.org/wiki/Shapefile) in size. Golang permits a much larger main-memory footprint to be used in an application there's no real desire for me to revisit this.
